TabletopTracker.WebMVC/Controllers/CategoryController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TabletopTracker.Models.Category;
using TabletopTracker.Services;

namespace TabletopTracker.WebMVC.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            var service = CreateCategoryService();
            var model = service.GetCategories();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateCategoryService();

            if (service.CreateCategory(model))
            {
                TempData["SaveResult"] = "Your category was created successfully.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Category could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateCategoryService();
            var model = svc.GetCategoryById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateCategoryService();
            var detail = service.GetCategoryById(id);
            var model = new CategoryEdit
            {
                CategoryId = detail.CategoryId,
                Name = detail.Name,
                Description = detail.Description
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CategoryEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.CategoryId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateCategoryService();

            if (service.UpdateCategory(model))
            {
                TempData["SaveResult"] = "Your game information was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your game information could not be updated.");
            return View();
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateCategoryService();
            var model = svc.GetCategoryById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateCategoryService();

            service.DeleteCategory(id);

            TempData["SaveResult"] = "Your game was deleted.";

            return RedirectToAction("Index");
        }

        private CategoryService CreateCategoryService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CategoryService(userId);
            return service;
        }
    }
}

TabletopTracker.WebMVC/Controllers/GameController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TabletopTracker.Models.Category;
using TabletopTracker.Models.Game;
using TabletopTracker.Models.Publisher;
using TabletopTracker.Services;

namespace TabletopTracker.WebMVC.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Index()
        {
            var service = CreateGameService();
            var model = service.GetGames();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            ViewBag.Publishers = new SelectList(GetPublishers(), "PublisherId", "Name");
            ViewBag.Categories = new SelectList(GetCategories(), "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GameCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateGameService();

            if (service.CreateGame(model))
            {
                TempData["SaveResult"] = "Your game was added successfully.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Game could not be added.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateGameService();
            var model = svc.GetGameById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateGameService();
            var detail = service.GetGameById(id);
            ViewBag.Publishers = new SelectList(GetPublishers(), "PublisherId", "Name");
            ViewBag.Categories = new SelectList(GetCategories(), "CategoryId", "Name");
            var model = new GameEdit
            {
                GameId = detail.GameId,
                Title = detail.Title,
                PublisherId = detail.PublisherId,
                CategoryId = detail.CategoryId,
                MinPlayers = detail.MinPlayers,
                MaxPlayers = detail.MaxPlayers,
                HavePlayed = detail.HavePlayed,
                Rating = detail.Rating
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, GameEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.GameId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateGameService();

            if(service.UpdateGame(model))
            {
                TempData["SaveResult"] = "Your game information was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your game information could not be updated.");
            return View();
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateGameService();
            var model = svc.GetGameById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateGameService();

            service.DeleteGame(id);

            TempData["SaveResult"] = "Your game was deleted.";

            return RedirectToAction("Index");
        }

        private GameService CreateGameService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new GameService(userId);
            return service;
        }

        private List<PublisherListItem> GetPublishers()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PublisherService(userId);
            var publishers = service.GetPublishers().OrderBy(p => p.Name).ToList();

            return publishers;
        }

        private List<CategoryListItem> GetCategories()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CategoryService(userId);
            var categories = service.GetCategories().OrderBy(c => c.Name).ToList();

            return categories;
        }
    }
}

TabletopTracker.WebMVC/Controllers/PublisherController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TabletopTracker.Models.Publisher;
using TabletopTracker.Services;

namespace TabletopTracker.WebMVC.Controllers
{
    [Authorize]
    public class PublisherController : Controller
    {
        // GET: Publisher
        public ActionResult Index()
        {
            var service = CreatePublisherService();
            var model = service.GetPublishers();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PublisherCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreatePublisherService();

            if (service.CreatePublisher(model))
            {
                TempData["SaveResult"] = "The publisher was created successfully.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Publisher could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreatePublisherService();
            var model = svc.GetPublisherById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreatePublisherService();
            var detail = service.GetPublisherById(id);
            var model = new PublisherEdit
            {
                PublisherId = detail.PublisherId,
                Name = detail.Name,
                Website = detail.Website
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PublisherEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PublisherId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreatePublisherService();

            if (service.UpdatePublisher(model))
            {
                TempData["SaveResult"] = "Publisher information was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Publisher information could not be updated.");
            return View();
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreatePublisherService();
            var model = svc.GetPublisherById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreatePublisherService();

            service.DeletePublisher(id);

            TempData["SaveResult"] = "This publisher was deleted.";

            return RedirectToAction("Index");
        }

        private PublisherService CreatePublisherService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PublisherService(userId);
            return service;
        }
    }
}

TabletopTracker.WebMVC/Controllers/SessionController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TabletopTracker.Models.Game;
using TabletopTracker.Models.Session;
using TabletopTracker.Services;

namespace TabletopTracker.WebMVC.Controllers
{
    [Authorize]
    public class SessionController : Controller
    {
        // GET: Session
        public ActionResult Index()
        {
            var service = CreateSessionService();
            var model = service.GetSessions();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            ViewBag.Games = new SelectList(GetGames(), "GameId", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SessionCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateSessionService();

            if (service.CreateSession(model))
            {
                TempData["SaveResult"] = "Your session was created successfully.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your session could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateSessionService();
            var model = svc.GetSessionById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateSessionService();
            var detail = service.GetSessionById(id);
            ViewBag.Games = new SelectList(GetGames(), "GameId", "Title");
            var model = new SessionEdit
            {
                SessionId = detail.SessionId,
                GameId = detail.GameId,
                Date = detail.Date,
                Players = detail.Players, 
                Notes = detail.Notes
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SessionEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.SessionId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateSessionService();

            if (service.UpdateSession(model))
            {
                TempData["SaveResult"] = "Your session information was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your session information could not be updated.");
            return View();
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateSessionService();
            var model = svc.GetSessionById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateSessionService();

            service.DeleteSession(id);

            TempData["SaveResult"] = "Your session was deleted.";

            return RedirectToAction("Index");
        }

        private SessionService CreateSessionService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SessionService(userId);
            return service;
        }

        private List<GameListItem> GetGames()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new GameService(userId);
            var games = service.GetGames().OrderBy(g => g.Title).ToList();

            return games;
        }
    }
}

TabletopTracker.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tabletop Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary py-3">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Tabletop Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("Index", "Game")">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("Index", "Category")">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("Index", "Publisher")">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("Index", "Session")">Sessions</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <!--<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tabletop Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">-->
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <!--@if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Games", "Index", "Game")</li>
                        <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                        <li>@Html.ActionLink("Publishers", "Index", "Publisher")</li>
                        <li>@Html.ActionLink("Sessions", "Index", "Session")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>-->
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                <!--</ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>-->
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        <footer class="text-center mt-2">
            <p>&copy; @DateTime.Now.Year - Tabletop Tracker by Adam Sadler</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<style>
    .navbar {
        padding: 10px;
    }
</style>